- name: setup consul configuration file
  template: src=templates/consul_server.json.j2 dest={{ config_dir }}/consul.json owner=root group=root mode=0644

- name: setup consul service file
  template: src=templates/consul.service.j2 dest=/etc/systemd/system/consul.service owner=root group=root mode=0644

- name: start consul
  service: name=consul state=started

- wait_for: port=8400

- name: create cluster
  command: "{{ bin_dir }}/consul join {{ hostvars['manager-0'].ansible_eth0.ipv4.address }} {{ hostvars['manager-1'].ansible_eth0.ipv4.address }} {{ hostvars['manager-2'].ansible_eth0.ipv4.address }}"

- name: setup nomad server config
  template: src=templates/nomad_server.hcl.j2 dest={{ config_dir }}/nomad/node.hcl owner=root group=root mode=0644

- name: setup nomad service file
  template: src=templates/nomad.service.j2 dest=/etc/systemd/system/nomad.service owner=root group=root mode=0644

- name: start nomad
  service: name=nomad state=started
