- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- apt_key:
    keyserver: "hkp://ha.pool.sks-keyservers.net:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D

- apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: present
    update_cache: yes

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
    - docker-engine
