- name: setup client config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  with_items:
    - { src: templates/consul_client.json.j2, dest: "{{ config_dir }}/consul.json"       }
    - { src: templates/nomad_client.hcl.j2,   dest: "{{ config_dir }}/nomad/node.hcl"  }

- name: download flannel
  get_url:
    url: "https://github.com/coreos/flannel/releases/download/v0.6.2/flannel-v0.6.2-linux-amd64.tar.gz"
    dest: /tmp/flanneld.tar.gz

- unarchive:
    src: /tmp/flanneld.tar.gz
    dest: /tmp/
    copy: no

- command: "{{ item }}"
  with_items:
    - "cp /tmp/flanneld {{ bin_dir }}"
    - "cp /tmp/mk-docker-opts.sh {{ bin_dir }}"

- template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  with_items:
    - { src: templates/flanneld.service.j2, dest: "/etc/systemd/system/flanneld.service" }
    - { src: templates/flanneld.config.j2,  dest: "/etc/default/flanneld"                }

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- apt_key:
    keyserver: "hkp://ha.pool.sks-keyservers.net:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D

- apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: present
    update_cache: yes

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
    - docker-engine

- file:
    path: "/etc/systemd/system/docker.service.d"
    mode: "0755"
    state: directory

- template:
    src: templates/docker.conf.j2
    dest: "/etc/systemd/system/docker.service.d/docker.conf"
    owner: root
    group: root

- service:
    name: docker
    enabled: yes
    state: reloaded

- service:
    name: docker
    enabled: yes
    state: restarted

